"""会影响缓存、压缩和投影可信度的策略版本。"""

SYSTEM_PROMPT_VERSION = "v1"
COMPACTION_STRATEGY_VERSION = "v1"
TASK_BOUNDARY_TOOL_VERSION = "v1"
TOOL_RESULT_NORMALIZER_VERSION = "v1"
CONTEXT_PROJECTION_VERSION = "v1"
CHECKPOINT_STRATEGY_VERSION = "v1"
